version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: web-nginx
    volumes:
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d
      - ./projects:/var/www
      - web_assets:/var/www/web/app/web/assets
      - sockets:/var/run
    ports:
      - 80:80
    environment:
      TZ: Europe/Kiev

  fpm:
    build: ./docker-build/fpm
    container_name: web-fpm
    tty: true
    volumes:
      - ./docker-config/fpm/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./docker-config/fpm/cron.d:/etc/cron.d
      - ./projects:/var/www
      - web_assets:/var/www/web/app/web/assets
      - sockets:/var/run
    environment:
      GITHUB_API_TOKEN:
      COMPOSER_ALLOW_SUPERUSER: 1
      PHP_ENABLE_XDEBUG: 1
      #XDEBUG_CONFIG: remote_host=172.17.0.1 # LINUX/MAC
      XDEBUG_CONFIG: remote_host=10.0.75.1 # WINDOWS
      TZ: Europe/Kiev

  db:
    image: mysql:latest
    container_name: web-db
    volumes:
      - ./docker-config/db:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
      - sockets:/var/run
    command: ["/bin/sh", "-c", "mkdir -p /var/run/mysqld && chmod -R 777 /var/run/mysqld/ && docker-entrypoint.sh mysqld --user=root --default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Kiev

  redis:
    image: redis:latest
    container_name: web-redis
    volumes:
      - ./docker-config/redis/redis.conf:/etc/redis.conf
      - sockets:/var/run
    command: ["/bin/sh", "-c", "mkdir -p /var/run/redis && chmod -R 777 /var/run/redis/ && docker-entrypoint.sh redis-server /etc/redis.conf"]
    environment:
      TZ: Europe/Kiev

  mailcatcher:
    image: dockage/mailcatcher
    container_name: web-mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    environment:
      TZ: Europe/Kiev

volumes:
  db_data:
  web_assets:
  sockets:

networks:
  default:
    driver: bridge
