version: "3"

services:

  nginx:
    image: nginx:latest
    container_name: web-nginx
    volumes:
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./projects:/var/www
      - web_assets:/var/www/web/app/web/assets
    ports:
      - 80:80
    environment:
      TZ: Europe/Kiev

  fpm:
    build: ./docker-containers/fpm
    container_name: web-fpm
    tty: true
    expose:
      - 9000
    volumes:
      - ./docker-config/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./projects:/var/www
      - web_assets:/var/www/web/app/web/assets
      - db_socket:/var/run/mysqld
      - redis_socket:/var/run/redis
    environment:
      GITHUB_API_TOKEN:
      COMPOSER_ALLOW_SUPERUSER: 1
      PHP_ENABLE_XDEBUG: 1
      #XDEBUG_CONFIG: remote_host=172.17.0.1 # LINUX/MAC
      XDEBUG_CONFIG: remote_host=10.0.75.1 # WINDOWS
      TZ: Europe/Kiev

  db:
    image: mysql:latest
    container_name: web-db
    volumes:
      - ./docker-config/db:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
      - db_socket:/var/run/mysqld
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Kiev

  redis:
    image: redis:latest
    container_name: web-redis
    volumes:
      - ./docker-config/redis/redis.conf:/etc/redis.conf
      - redis_socket:/var/run/redis
    command: "redis-server /etc/redis.conf"
    environment:
      TZ: Europe/Kiev

  mailcatcher:
    image: dockage/mailcatcher
    container_name: web-mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    environment:
      TZ: Europe/Kiev

volumes:
  db_data:
  db_socket:
  web_assets:
  redis_socket:
