version: "3"

services:

  nginx:
    image: library/nginx:latest
    container_name: web-nginx
    volumes:
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d
      - ./projects:/var/www
      - web_assets:/var/www/web/app/web/assets
      - sockets:/tmp
    ports:
      - 80:80
    depends_on:
      - fpm
    environment:
      TZ: Europe/Kiev

  fpm:
    build: ./docker-build/fpm
    container_name: web-fpm
    tty: true
    volumes:
      #- ./docker-config/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker-config/fpm/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./docker-config/fpm/cron.d/php-fpm:/etc/cron.d/php-fpm
      - ./projects:/var/www
      - web_assets:/var/www/web/app/web/assets
      - sockets:/tmp
    environment:
      GITHUB_API_TOKEN:
      COMPOSER_ALLOW_SUPERUSER: 1
      PHP_ENABLE_XDEBUG: 1
      #XDEBUG_CONFIG: remote_host=172.17.0.1 # LINUX/MAC
      XDEBUG_CONFIG: remote_host=10.0.75.1 # WINDOWS
      TZ: Europe/Kiev

  db:
    image: library/mysql:latest
    container_name: web-db
    volumes:
      - ./docker-config/db:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
      - sockets:/tmp
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Kiev

  redis:
    image: library/redis:latest
    container_name: web-redis
    volumes:
      - ./docker-config/redis/redis.conf:/etc/redis.conf
      - sockets:/tmp
    command: ["/etc/redis.conf"]
    environment:
      TZ: Europe/Kiev

  mailcatcher:
    image: dockage/mailcatcher
    container_name: web-mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    environment:
      TZ: Europe/Kiev

volumes:
  db_data:
  web_assets:
  sockets:
