version: "3"

services:

  nginx:
    image: nginx:stable
    container_name: web-nginx
    links:
      - fpm
    volumes:
      - ./docker-config/nginx/conf.d:/etc/nginx/conf.d
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./projects:/var/www
      - assets_backend:/var/www/web/backend/web/assets
      - assets_frontend:/var/www/web/frontend/web/assets
    ports:
      - 80:80
    environment:
      TZ: Europe/Kiev

  fpm:
    build: ./docker-containers/fpm
    container_name: web-fpm
    tty: true
    expose:
      - 9000
    links:
      - db
      - redis
      - memcached
      - mailcatcher
    volumes:
      # TODO: в папке conf.d уже есть конфиги от docker-php-ext-*
      - ./docker-config/fpm/conf.d/memcached.ini:/usr/local/etc/php/conf.d/memcached.ini
      - ./docker-config/fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker-config/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./projects:/var/www
      - assets_backend:/var/www/web/backend/web/assets
      - assets_frontend:/var/www/web/frontend/web/assets
    environment:
      GITHUB_API_TOKEN:
      COMPOSER_ALLOW_SUPERUSER: 1
      PHP_ENABLE_XDEBUG: 1
      #XDEBUG_CONFIG: remote_host=172.17.0.1 # LINUX/MAC
      XDEBUG_CONFIG: remote_host=10.0.75.1 # WINDOWS
      TZ: Europe/Kiev

  db:
    image: mysql:latest
    container_name: web-db
    ports:
      - 3306:3306
    volumes:
      - ./docker-config/db:/usr/local/mysqlconf
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Kiev

  redis:
    image: redis:latest
    container_name: web-redis
    command: --requirepass root
    ports:
      - 6379:6379
    environment:
      TZ: Europe/Kiev

  memcached:
    image: memcached:latest
    container_name: web-memcached
    environment:
      TZ: Europe/Kiev

  mailcatcher:
    image: dockage/mailcatcher
    container_name: web-mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    environment:
      TZ: Europe/Kiev

volumes:
  dbdata:
  assets_backend:
  assets_frontend:
